apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: test-container
    image: registry.aliyuncs.com/jimmycmh/busybox
    command: [ "/bin/sh", "-c", "env" ]
    volumeMounts:
      - mountPath: /etc/secret/
        name: myothersecret
  restartPolicy: Never
  volumes:
  - name: myothersecret
    secret:
      secretName: myothersecret
