apiVersion: v1
kind: Service
metadata:
  labels:
    app: test1
  name: test2
  namespace: default
spec:
  type: NodePort
  ports:
  - name: s-tcp
    nodePort: 8582
    port: 8582
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-ds



# 自己建了个,转发server
